- name: Remove Podman and compatibility packages
  ansible.builtin.yum:
    name:
      - podman
      - podman-docker
    state: absent

- name: Remove conflicting Docker and Podman packages
  ansible.builtin.yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - podman
      - runc
    state: absent

- name: Add the Docker CE repository
  ansible.builtin.command: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Verify Docker installation
  ansible.builtin.command: docker --version
  register: docker_version

- name: Debug Docker version
  debug:
    msg: "Docker installed: {{ docker_version.stdout }}"

- name: Run hello-world to verify Docker functionality
  ansible.builtin.command: docker run hello-world
