- name: Determine Ansible host IP
  ansible.builtin.set_fact:
    dns_server_ip: "{{ ansible_default_ipv4.address }}"
    delegate_to: localhost
  #run_once: true
  become: true

- name: Backup existing resolv.conf
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: /etc/resolv.conf.bak
    remote_src: yes
    backup: true
  become: true

- name: Retrieve DNS server IP from control host
  ansible.builtin.set_fact:
    dns_server_ip: "{{ hostvars['localhost']['dns_server_ip'] }}"
  #run_once: true

- name: Set Ansible host as DNS server
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: "nameserver {{ dns_server_ip }}"
    insertbefore: '^nameserver .*'
    state: present
  become: true
