- name: Include tasks for the DNS server
  include_tasks: dnsmasq.yaml
  when: "'local' in inventory_hostname"
  #when: inventory_hostname == "ansible_host"

- name: Configure other nodes to use Ansible host as DNS server
  include_tasks: configure_dns_clients.yaml
  when: inventory_hostname != "ansible_host"
