---
- name: Delete RKE2
  hosts: all
  vars_files:
    - group_vars/rke2_nodes.yml
  tasks:
    - name: Stop and disable RKE2 server
      systemd:
        name: rke2-server
        enabled: no
        state: stopped

    - name: Remove RKE2 binaries and configuration
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/rancher/rke2
        - /var/lib/rancher/rke2
        - /var/lib/kubelet
