---
- name: Install RKE2
  hosts: all
  vars_files:
    - group_vars/rke2_nodes.yml
  tasks:
    - name: Update system and install required dependencies
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ yum_packages }}"

    - name: Install RKE2
      shell: |
        curl -sfL https://get.rke2.io | INSTALL_RKE2_VERSION={{ rke2_version }} sh -

    - name: Enable and start RKE2 server
      systemd:
        name: rke2-server
        enabled: yes
        state: started

