all:
  vars:
    ansible_user: root
  children:
    dns_servers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: 192.168.0.90
    masters:
      hosts:
        master1:
          ansible_host: 192.168.0.91
          rke2_role: server
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.0.92
          rke2_role: agent
    rke2_servers:
      children:
        masters:
        workers:
