# Removing firewalld due to conflicts with default networking
# https://docs.rke2.io/known_issues#firewalld-conflicts-with-default-networking
- name: Remove firewalld 
  ansible.builtin.dnf:
    name: firewalld
    state: absent

- name: Install nftables
  ansible.builtin.dnf:
    name: nftables
    state: latest

- name: Enable and start nftables service
  ansible.builtin.systemd:
    name: nftables
    state: started
    enabled: yes

- name: Create nftables ruleset table for rke2
  ansible.builtin.template:
    src: rke2.nft.j2
    dest: /etc/nftables/rke2.nft

- name: Load nftables ruleset
  ansible.builtin.command: nft -f /etc/nftables/rke2.nft

- name: Save nftables ruleset
  ansible.builtin.shell: |
    nft list ruleset > /etc/sysconfig/nftables.conf

- name: Display nftables ruleset
  ansible.builtin.command: nft list ruleset
  register: nft_status