---

# RKE2 Version to be installed
rke2_version: "v1.22.0+rke2r1"

# Kubernetes Configuration
kube_api_bind_port: 6443
kube_pod_network_cidr: "10.42.0.0/16"

# System Configuration
yum_packages:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2

# Docker Configuration (containerd is installed by default with RKE2)
docker_version: "latest"

# RKE2 Paths
kubeconfig_path: "/root/.kube/config"

