---
# Main tasks for setting up the HTTP server using Podman

- name: Ensure Podman is installed
  dnf:
    name: podman
    state: present
  tags: http

- name: Ensure Podman container image for HTTP server is pulled
  containers.podman.podman_image:
    name: "{{ httpd_container_image }}"
    state: present
  tags: http

- name: Create a directory for HTTP server files
  file:
    path: /var/www/html
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags: http

- name: Deploy Kickstart configuration for each target host
  template:
    src: ks.cfg.j2
    dest: "/var/www/html/ks-{{ inv_hostname }}.cfg"
  with_items: "{{ groups['target_hosts'] }}"
  loop_control:
    loop_var: inv_hostname
  tags: http

- name: Set correct permissions for Kickstart files
  file:
    path: "/var/www/html/ks-{{ inv_hostname }}.cfg"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ groups['target_hosts'] }}"
  loop_control:
    loop_var: inv_hostname
  tags: http

- name: Deploy the test HTML page
  template:
    src: templates/test_page.html.j2
    dest: /var/www/html/index.html
    mode: '0644'
  tags: http

- name: Start the HTTP server container with Podman
  containers.podman.podman_container:
    name: httpd_server
    image: "{{ httpd_container_image }}"
    state: started
    ports:
      - "{{ http_port }}:80"
    volumes:
      - /var/www/html:/usr/local/apache2/htdocs:Z
    restart_policy: unless-stopped
  tags: http
