---
- name: Deploy RKE2 Servers
  hosts: masters
  become: true
  roles:
    - role: common
    - role: firewall
      tags: firewall
    - role: docker
      tags: docker
    - role: rke2
  vars:
    rke2_role: "server"

- name: Deploy RKE2 Agents
  hosts: workers
  become: true
  roles:
    - role: common
    - role: firewall
      tags: firewall
    - role: docker
      tags: docker
    - role: rke2
  vars:
    rke2_role: "agent"

- name: Deploy rancher
  hosts: masters
  become: true
  roles:
    - role: rancher
      tags: rancher
  vars:
    rke2_role: "server"