all:
  vars:
    ansible_user: root
  children:
    masters:
      hosts:
        master1:
          ansible_host: 10.10.25.199
          rke2_role: server
    workers:
      hosts:
        worker1:
          ansible_host: 10.10.25.136
          rke2_role: agent
