- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest

- name: Install basic tools
  ansible.builtin.yum:
    name:
      - curl
      - tar
    state: present

- name: Ensure hostname matches inventory
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  become: true
