all:
  vars:
    ansible_user: root
  children:
    dns_servers:
      hosts:
        localhost:
          ansible_connection: local
          ansible_host: 10.10.25.163
    masters:
      hosts:
        master1:
          ansible_host: 10.10.25.161
          rke2_role: server
    workers:
      hosts:
        worker1:
          ansible_host: 10.10.25.162
          rke2_role: agent
